# Generated by Django 4.2.9 on 2025-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/'),
        ),
    ]
