# Generated by Django 4.2.9 on 2025-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_driverdocument_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('default_ride_cost', 'Default Ride Cost (Tenge)'), ('fare_boost_amount', 'Fare Boost Amount (Tenge)'), ('max_fare_boosts', 'Maximum Fare Boosts Allowed')], max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
                'db_table': 'app_settings',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='fare_boosts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
