# Driver Bot Conversation States
(LANGUAGE, REGISTRATION, DOCUMENT_UPLOAD, VEHICLE_INFO,
 VERIFICATION_PENDING, MAIN_MENU, LOCATION_UPDATE,
 RIDE_NOTIFICATION, RIDE_MANAGEMENT, PHONE_VERIFICATION) = range(10)
